name: Deployment Workflow ERO

on:
  push:
    branches:
      - master
      - develop
  workflow_dispatch:


jobs:
  my_first_job:
    name: My first job
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name }}
    steps:
      - name: My first step - check out repository
        run:  |
          echo "::debug::Hello World"
          echo "MYSECRET: ${{secrets.MYSECRET}}"
          echo "env my scret : ${{env.MYSECRET}}"
          echo "env my var : ${{vars.MYVAR}}"
          echo "github ref name: ${{ github.ref_name }}"
